stages:
  - initial
  - scan
  - build
  - deploy
  - test

include:
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.4.1'
    file: 'ci/template.gitlab-ci.yml'

Deploy--Rabbitmq:
  stage: deploy
  image:
    name: alpine/k8s:1.25.9
  variables:
    iiidevops: deployed-environments
  script:
  - env
  - envsubst < k8s/kustomization.yaml.tmp >  k8s/kustomization.yaml
  - kubectl kustomize k8s/ | kubectl apply -f -
  only:
    - master

Deploy--Wait Redis :
  stage: deploy
  image:
    name: iiiorg/iiidevops-cli:0.0.6
    entrypoint: [ "" ]
  variables:
    iiidevops: deployed-environments
    max_wait: 128
    namespace: ${CI_PROJECT_NAME}
    deploy_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-rbmq
  needs:
    - "Deploy--Rabbitmq"
  script:
    - deploy-wait.pl
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/


