stages:
- name: Integration--initial pipeline
  iiidevops: initial-pipeline
  steps:
  - envFrom:
    - sourceKey: api-origin
      sourceName: nexus
      targetKey: api_origin
    runScriptConfig:
      image: iiiorg/iiidevops-cli:0.0.4
      shellScript: curl --location -s --request POST ${api_origin}/rancher/delete_app
        --form project_name=${CICD_GIT_REPO_NAME} --form branch_name=${CICD_GIT_BRANCH}
        && count-src.pl
- name: Deploy--RabbitMQ
  iiidevops: deployed-environments
  steps:
  - applyYamlConfig:
      path: ./k8s/rabbitmq-deployment.yaml
  when:
    branch:
      include:
      - master
- name: Deploy--RabbitMQ-service
  iiidevops: deployed-environments
  steps:
  - applyYamlConfig:
      path: ./k8s/rabbitmq-service.yaml
  when:
    branch:
      include:
      - master
- name: Deploy--Wait RabbitMQ deployment
  iiidevops: deployed-environments
  steps:
  - env:
      deploy_name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-rbmq
      max_wait: 128
      namespace: ${CICD_GIT_REPO_NAME}
    envFrom:
    - sourceKey: API_TOKEN
      sourceName: pipeline-api-key
      targetKey: rancher_api_token
    - sourceKey: rancher-url
      sourceName: rancher
      targetKey: rancher_url
    runScriptConfig:
      image: iiiorg/iiidevops-cli:0.0.4
      shellScript: rancher login ${rancher_url} -t ${rancher_api_token} --skip-verify;
        deploy-wait.pl
  when:
    branch:
      include:
      - master
