apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  type: NodePort
  ports:
    - name: rbmq-tcp-15672
      protocol: TCP
      port: 15672
    - name: rbmq-tcp-5672
      protocol: TCP
      port: 5672
