apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rbmq
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: harbor-local
      containers:
      - image: rabbitmq:3-management
        name: rbmq
        ports:
        - containerPort: 15672
          name: rbmq-tcp-15672
        - containerPort: 5672
          name: rbmq-tcp-5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
